---
title: Jekyll Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Process PA
description: Committee meetings made simple
sass:
  style: compressed
