paths:
  uploads: uploads
  static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
data_config: {}
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
