FROM ruby:3.0-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential git nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN gem install bundler:2.4.22

WORKDIR /srv/jekyll

ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    BUNDLE_FORCE_RUBY_PLATFORM=true
